numb = int(input("Enter a number"))
print ("The multiplication table of {} from 1 to 10 is".format(numb))
print ( numb * 1)
print (numb * 2)
print (numb * 3)
print (numb * 4)
print (numb * 5)
print (numb * 6)
print (numb * 7)
print (numb * 8)
print (numb * 9)
print (numb * 10)
