#Import image
FROM nginx

#set working directory
WORKDIR /app

#set port
EXPOSE 80

#Copy files
COPY /html/index.html /usr/share/nginx/html/
COPY /html/register.html /usr/share/nginx/html/
COPY /html/signup.html /usr/share/nginx/html/

