#Import image
FROM httpd

#set working directory
WORKDIR /app

#set port
EXPOSE 80

#Copy files
COPY /html/index.html /usr/local/apache2/htdocs/
COPY /html/register.html /usr/local/apache2/htdocs/
COPY /html/signup.html /usr/local/apache2/htdocs/

